bible_dictionary = {
    # 구약 성경 (Old Testament)
    "GEN": {"korean_name": "창세기", "korean_concise_name": "창", "full_name": "Genesis", "chapter_num": 50, "order": 1, "is_old_testament": True},
    "EXO": {"korean_name": "출애굽기", "korean_concise_name": "출", "full_name": "Exodus", "chapter_num": 40, "order": 2, "is_old_testament": True},
    "LEV": {"korean_name": "레위기", "korean_concise_name": "레", "full_name": "Leviticus", "chapter_num": 27, "order": 3, "is_old_testament": True},
    "NUM": {"korean_name": "민수기", "korean_concise_name": "민", "full_name": "Numbers", "chapter_num": 36, "order": 4, "is_old_testament": True},
    "DEU": {"korean_name": "신명기", "korean_concise_name": "신", "full_name": "Deuteronomy", "chapter_num": 34, "order": 5, "is_old_testament": True},
    "JOS": {"korean_name": "여호수아", "korean_concise_name": "수", "full_name": "Joshua", "chapter_num": 24, "order": 6, "is_old_testament": True},
    "JDG": {"korean_name": "사사기", "korean_concise_name": "삿", "full_name": "Judges", "chapter_num": 21, "order": 7, "is_old_testament": True},
    "RUT": {"korean_name": "룻기", "korean_concise_name": "룻", "full_name": "Ruth", "chapter_num": 4, "order": 8, "is_old_testament": True},
    "1SA": {"korean_name": "사무엘상", "korean_concise_name": "삼상", "full_name": "1 Samuel", "chapter_num": 31, "order": 9, "is_old_testament": True},
    "2SA": {"korean_name": "사무엘하", "korean_concise_name": "삼하", "full_name": "2 Samuel", "chapter_num": 24, "order": 10, "is_old_testament": True},
    "1KI": {"korean_name": "열왕기상", "korean_concise_name": "왕상", "full_name": "1 Kings", "chapter_num": 22, "order": 11, "is_old_testament": True},
    "2KI": {"korean_name": "열왕기하", "korean_concise_name": "왕하", "full_name": "2 Kings", "chapter_num": 25, "order": 12, "is_old_testament": True},
    "1CH": {"korean_name": "역대상", "korean_concise_name": "대상", "full_name": "1 Chronicles", "chapter_num": 29, "order": 13, "is_old_testament": True},
    "2CH": {"korean_name": "역대하", "korean_concise_name": "대하", "full_name": "2 Chronicles", "chapter_num": 36, "order": 14, "is_old_testament": True},
    "EZR": {"korean_name": "에스라", "korean_concise_name": "스", "full_name": "Ezra", "chapter_num": 10, "order": 15, "is_old_testament": True},
    "NEH": {"korean_name": "느헤미야", "korean_concise_name": "느", "full_name": "Nehemiah", "chapter_num": 13, "order": 16, "is_old_testament": True},
    "EST": {"korean_name": "에스더", "korean_concise_name": "더", "full_name": "Esther", "chapter_num": 10, "order": 17, "is_old_testament": True},
    "JOB": {"korean_name": "욥기", "korean_concise_name": "욥", "full_name": "Job", "chapter_num": 42, "order": 18, "is_old_testament": True},
    "PSA": {"korean_name": "시편", "korean_concise_name": "시", "full_name": "Psalms", "chapter_num": 150, "order": 19, "is_old_testament": True},
    "PRO": {"korean_name": "잠언", "korean_concise_name": "잠", "full_name": "Proverbs", "chapter_num": 31, "order": 20, "is_old_testament": True},
    "ECC": {"korean_name": "전도서", "korean_concise_name": "전", "full_name": "Ecclesiastes", "chapter_num": 12, "order": 21, "is_old_testament": True},
    "SNG": {"korean_name": "아가", "korean_concise_name": "아", "full_name": "Song of Solomon", "chapter_num": 8, "order": 22, "is_old_testament": True},
    "ISA": {"korean_name": "이사야", "korean_concise_name": "사", "full_name": "Isaiah", "chapter_num": 66, "order": 23, "is_old_testament": True},
    "JER": {"korean_name": "예레미야", "korean_concise_name": "렘", "full_name": "Jeremiah", "chapter_num": 52, "order": 24, "is_old_testament": True},
    "LAM": {"korean_name": "예레미야애가", "korean_concise_name": "애", "full_name": "Lamentations", "chapter_num": 5, "order": 25, "is_old_testament": True},
    "EZK": {"korean_name": "에스겔", "korean_concise_name": "겔", "full_name": "Ezekiel", "chapter_num": 48, "order": 26, "is_old_testament": True},
    "DAN": {"korean_name": "다니엘", "korean_concise_name": "단", "full_name": "Daniel", "chapter_num": 12, "order": 27, "is_old_testament": True},
    "HOS": {"korean_name": "호세아", "korean_concise_name": "호", "full_name": "Hosea", "chapter_num": 14, "order": 28, "is_old_testament": True},
    "JOL": {"korean_name": "요엘", "korean_concise_name": "욜", "full_name": "Joel", "chapter_num": 3, "order": 29, "is_old_testament": True},
    "AMO": {"korean_name": "아모스", "korean_concise_name": "암", "full_name": "Amos", "chapter_num": 9, "order": 30, "is_old_testament": True},
    "OBA": {"korean_name": "오바댜", "korean_concise_name": "옵", "full_name": "Obadiah", "chapter_num": 1, "order": 31, "is_old_testament": True},
    "JON": {"korean_name": "요나", "korean_concise_name": "욘", "full_name": "Jonah", "chapter_num": 4, "order": 32, "is_old_testament": True},
    "MIC": {"korean_name": "미가", "korean_concise_name": "미", "full_name": "Micah", "chapter_num": 7, "order": 33, "is_old_testament": True},
    "NAM": {"korean_name": "나훔", "korean_concise_name": "나", "full_name": "Nahum", "chapter_num": 3, "order": 34, "is_old_testament": True},
    "HAB": {"korean_name": "하박국", "korean_concise_name": "합", "full_name": "Habakkuk", "chapter_num": 3, "order": 35, "is_old_testament": True},
    "ZEP": {"korean_name": "스바냐", "korean_concise_name": "습", "full_name": "Zephaniah", "chapter_num": 3, "order": 36, "is_old_testament": True},
    "HAG": {"korean_name": "학개", "korean_concise_name": "학", "full_name": "Haggai", "chapter_num": 2, "order": 37, "is_old_testament": True},
    "ZEC": {"korean_name": "스가랴", "korean_concise_name": "슥", "full_name": "Zechariah", "chapter_num": 14, "order": 38, "is_old_testament": True},
    "MAL": {"korean_name": "말라기", "korean_concise_name": "말", "full_name": "Malachi", "chapter_num": 4, "order": 39, "is_old_testament": True},

    # 신약 성경 (New Testament)
    "MAT": {"korean_name": "마태복음", "korean_concise_name": "마", "full_name": "Matthew", "chapter_num": 28, "order": 40, "is_old_testament": False},
    "MRK": {"korean_name": "마가복음", "korean_concise_name": "막", "full_name": "Mark", "chapter_num": 16, "order": 41, "is_old_testament": False},
    "LUK": {"korean_name": "누가복음", "korean_concise_name": "눅", "full_name": "Luke", "chapter_num": 24, "order": 42, "is_old_testament": False},
    "JHN": {"korean_name": "요한복음", "korean_concise_name": "요", "full_name": "John", "chapter_num": 21, "order": 43, "is_old_testament": False},
    "ACT": {"korean_name": "사도행전", "korean_concise_name": "행", "full_name": "Acts", "chapter_num": 28, "order": 44, "is_old_testament": False},
    "ROM": {"korean_name": "로마서", "korean_concise_name": "롬", "full_name": "Romans", "chapter_num": 16, "order": 45, "is_old_testament": False},
    "1CO": {"korean_name": "고린도전서", "korean_concise_name": "고전", "full_name": "1 Corinthians", "chapter_num": 16, "order": 46, "is_old_testament": False},
    "2CO": {"korean_name": "고린도후서", "korean_concise_name": "고후", "full_name": "2 Corinthians", "chapter_num": 13, "order": 47, "is_old_testament": False},
    "GAL": {"korean_name": "갈라디아서", "korean_concise_name": "갈", "full_name": "Galatians", "chapter_num": 6, "order": 48, "is_old_testament": False},
    "EPH": {"korean_name": "에베소서", "korean_concise_name": "엡", "full_name": "Ephesians", "chapter_num": 6, "order": 49, "is_old_testament": False},
    "PHP": {"korean_name": "빌립보서", "korean_concise_name": "빌", "full_name": "Philippians", "chapter_num": 4, "order": 50, "is_old_testament": False},
    "COL": {"korean_name": "골로새서", "korean_concise_name": "골", "full_name": "Colossians", "chapter_num": 4, "order": 51, "is_old_testament": False},
    "1TH": {"korean_name": "데살로니가전서", "korean_concise_name": "살전", "full_name": "1 Thessalonians", "chapter_num": 5, "order": 52, "is_old_testament": False},
    "2TH": {"korean_name": "데살로니가후서", "korean_concise_name": "살후", "full_name": "2 Thessalonians", "chapter_num": 3, "order": 53, "is_old_testament": False},
    "1TI": {"korean_name": "디모데전서", "korean_concise_name": "딤전", "full_name": "1 Timothy", "chapter_num": 6, "order": 54, "is_old_testament": False},
    "2TI": {"korean_name": "디모데후서", "korean_concise_name": "딤후", "full_name": "2 Timothy", "chapter_num": 4, "order": 55, "is_old_testament": False},
    "TIT": {"korean_name": "디도서", "korean_concise_name": "딛", "full_name": "Titus", "chapter_num": 3, "order": 56, "is_old_testament": False},
    "PHM": {"korean_name": "빌레몬서", "korean_concise_name": "몬", "full_name": "Philemon", "chapter_num": 1, "order": 57, "is_old_testament": False},
    "HEB": {"korean_name": "히브리서", "korean_concise_name": "히", "full_name": "Hebrews", "chapter_num": 13, "order": 58, "is_old_testament": False},
    "JAS": {"korean_name": "야고보서", "korean_concise_name": "약", "full_name": "James", "chapter_num": 5, "order": 59, "is_old_testament": False},
    "1PE": {"korean_name": "베드로전서", "korean_concise_name": "벧전", "full_name": "1 Peter", "chapter_num": 5, "order": 60, "is_old_testament": False},
    "2PE": {"korean_name": "베드로후서", "korean_concise_name": "벧후", "full_name": "2 Peter", "chapter_num": 3, "order": 61, "is_old_testament": False},
    "1JN": {"korean_name": "요한1서", "korean_concise_name": "요1", "full_name": "1 John", "chapter_num": 5, "order": 62, "is_old_testament": False},
    "2JN": {"korean_name": "요한2서", "korean_concise_name": "요2", "full_name": "2 John", "chapter_num": 1, "order": 63, "is_old_testament": False},
    "3JN": {"korean_name": "요한3서", "korean_concise_name": "요3", "full_name": "3 John", "chapter_num": 1, "order": 64, "is_old_testament": False},
    "JUD": {"korean_name": "유다서", "korean_concise_name": "유", "full_name": "Jude", "chapter_num": 1, "order": 65, "is_old_testament": False},
    "REV": {"korean_name": "요한계시록", "korean_concise_name": "계", "full_name": "Revelation", "chapter_num": 22, "order": 66, "is_old_testament": False},
}

bibleKeys = [
  "GEN", "EXO", "LEV", "NUM", "DEU", 
  "JOS", "JDG", "RUT", "1SA", "2SA",
  "1KI", "2KI", "1CH", "2CH", "EZR",
  "NEH", "EST", "JOB", "PSA", "PRO",
  "ECC", "SNG", "ISA", "JER", "LAM",
  "EZK", "DAN", "HOS", "JOL", "AMO",
  "OBA", "JON", "MIC", "NAM", "HAB",
  "ZEP", "HAG", "ZEC", "MAL", "MAT",
  "MRK", "LUK", "JHN", "ACT", "ROM",
  "1CO", "2CO", "GAL", "EPH", "PHP",
  "COL", "1TH", "2TH", "1TI", "2TI",
  "TIT", "PHM", "HEB", "JAS", "1PE",
  "2PE", "1JN", "2JN", "3JN", "JUD",
  "REV"
  ]